### ISSUE TITLE
I am getting this error On Product Pages

### ISSUE THREAD

**Issue by ibunkerz** [varunsridharan/single-product-checkout-for-woocommerce#1]
Hi

T'm getting this error. Im using WP latest version and Woocommerce latest version

Notice: id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, apply_filters('woocommerce_add_to_cart_validation'), WP_Hook->apply_filters, call_user_func_array, WooCommerce_Single_Product_Checkout_Frontend->check_cart, WooCommerce_Single_Product_Checkout_Frontend->check_cart_contents, WooCommerce_Single_Product_Checkout_Frontend->get_product_ids_from_cart, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /home/xxxx.com/public_html/wp-includes/functions.php on line 4138

Please fix this. Im badly in need of this plugin to work properly. Thank you so much

**Comment by technofreaky** [comment]
Hi,

Sure i will fix it and release an update soon.

**Comment by ibunkerz** [comment]
Thank you so much in advance. i would love to send some love as donation to show my gratitude.  
Looking forward to have an update 😊

God bless you brother.

**Comment by technofreaky** [comment]
Hi,

Update pushed.

**Comment by ibunkerz** [comment]
Hi there. thanks for a quick response :)
I just updated the plugin And checked it. Still When I assign a product to go as a single checkout It works. But at a same time if i add more products available on my website on my cart I was able to, which I don't think are needed to be added. 
I thought when a product is assigned for single checkout it wont allow other products to be added and it should show error messages but no error messages its showing also. Im using WP default theme and no other plugin is activated except woocommerce and WooCommerce Single Product Checkout Plugin

Thanks in advance

Hope to see this fixed

**Comment by technofreaky** [comment]
Hi,

Bug fixed and updated pushed. also please note : update the plugin settings once after the update is done.

**Comment by ibunkerz** [comment]
Still bugs are there. It wasnt working even after updating the setting page so i decided to reinstall WP
and after that it was working perfectly accordingly. But after I installed some more plugins on my site It stopped working. I thought maybe its conflicting with some  plugin so i deactivated all the plugins except your plugin and the woocommerce latest version.

Still other products are getting adding on the cart along with the product that is assigned as single checkout product. 

It should work like this>> IF a single checkout product is added it should redirect the page to cart page BUT when general products are being added without single checkout should not make redirection to the Cart page.

Thank you so much for your quick replies and fixes. Your plugin is one of a kind and It will be helpful to many freelancer like me. Please fix the issues. 
JAI HIND
