### ISSUE TITLE
Not working when a variable product (with enabled single checkout) is added first

### ISSUE THREAD

**Issue by Incubali86** [varunsridharan/single-product-checkout-for-woocommerce#10]
Stauts:
I have a variable product with enabled single checkout.

Not working:
When I add the product (single checkout product variation) to the cart first, then add a "normal product" the plugin allows to add this second product.

**Comment by Carinlockhart** [comment]
I am still experiencing this issue.  If the variable product marked as single product checkout is added first, other items may be added to the cart after it.  Is there something I need to do for this to work?

**Comment by Carinlockhart** [comment]
Note - I verified everything works fine when its a simple product.
