### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by ibunkerz** [varunsridharan/single-product-checkout-for-woocommerce#11]
Hi mate 

Plugin is not working anymore. Min qty, max qty doesnt work. I checked and its not stopping other products to be added to the cart.

I am using the latest version of wordpress and woocommerce and everything on my dashboard is up to date.

Please fix the plugin. Can not use it :(

Thanks you so much in advance

**Comment by geopayme** [comment]
Has anyone picked up the development of this plug, it seems to be a great idea but the min/max does not work on WP 5+

**Comment by varunsridharan** [comment]
@geopayme hey i am really sorry i was tied up with some other projects so unable to work on it. i will be releasing / updating this plugin soon.

**Comment by geopayme** [comment]
I like to support the update can you send me what would it  cost to fix and
repair the 0 to 1 limitation I'll be happy to contribute

Regards

Antonis

**Comment by varunsridharan** [comment]
@geopayme thats so nice of you. :-)  i dont request a fixed cost my open source development. so if you would really like to contribute you can go head to https://paypal.me/varunsridharan23
