### ISSUE TITLE
Variable Product - additional items can be added to cart 

### ISSUE THREAD

**Issue by Carinlockhart** [varunsridharan/single-product-checkout-for-woocommerce#12]
I commented on the previous posting of this issue (April), but thought perhaps I should also enter a new ticket.  When my stand alone item is a simple product, everything works great.  If I change it to a variable product, users can then add additional products after the standalone product is in the cart.

**Comment by NicWhitham** [comment]
I have the same issue - it doesn't look as though this is going to be addressed

**Comment by varunsridharan** [comment]
@Carinlockhart @NicWhitham can you please explain me about it.

I tried to replicate but nope. its working good for me.
