### ISSUE TITLE
Compatible with WooCommerce Subscriptions

### ISSUE THREAD

**Issue by studio4** [varunsridharan/single-product-checkout-for-woocommerce#14]
I think we have a slightly different version, but to make it compatible with the Simple Subscription product, we had to add the following into __construct on class-admin-product-settings.php

add_action( 'save_post', array($this, 'save_meta'));

Previously, it was not saving the Single Product Checkout field settings.

**Comment by varunsridharan** [comment]
@studio4 sorry about the delayed response. the new version V1.0 should work with it.,
