### ISSUE TITLE
Plugin stops working after update

### ISSUE THREAD

**Issue by rjshreve** [varunsridharan/single-product-checkout-for-woocommerce#17]
Every time this plugin is updated through woocommerce built in update feature, the plugin stops working. It remains active and the plugin settings remain accurate along with the product settings but it does not work to prevent multiple items in the cart. I have to uninstall and reinstall and then re-select each product do have single item checkout enabled.

**Comment by varunsridharan** [comment]
@rjshreve i tried to replicate but i really can't 
it works as it should be

**Comment by rjshreve** [comment]
I'm not sure how else to describe this. It is continuously breaking and unfortunately, I'm going to have to switch to a new plugin because of it. When it breaks it costs us A LOT of money.

**Comment by MrFent** [comment]
Please fix, it no longer works after update, as described above

**Comment by varunsridharan** [comment]
@rjshreve sorry about the delay. 
Well i am not able to replicate the issue to fix it and i can understand. you are more than welcome to switch the plugin its upto you.
but i am still here and happy to fix issue i need more info 

@MrFent i am happy to fix but whats the exact issue ?
I really can't figure out the issue . i have tried every thing

Can you provide steps ?

**Comment by MrFent** [comment]
The plugin is active, but it simply doesn't do what it is meant to do. I have a product set to single product checkout. I add it to my cart, then go to another product, and it is also allowed to be added to cart. No messages saying that the other product needs to complete checkout first. This happens with both versions 1.1 and 1.2. If I revery back to 1.0, it starts working correctly again.
